# Generated by Django 2.2.1 on 2019-05-17 08:46

from django.db import migrations, models
import django.db.models.deletion
import dog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_kind', models.CharField(max_length=100)),
                ('breed_size', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dog_picture_counter', models.PositiveIntegerField(default=0)),
                ('dog_coat_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dog_coat_color', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.ImageField(upload_to=dog.models.pic_name_policy)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.Dog')),
            ],
        ),
    ]
