# Generated by Django 2.2.1 on 2019-05-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField()),
                ('breed', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='dog_picture_represented',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_picture_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
