# Generated by Django 2.2.1 on 2019-05-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DogInput',
        ),
    ]
