# Generated by Django 2.2.1 on 2019-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20190520_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
