# Generated by Django 2.2.1 on 2019-05-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_delete_doginput'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.ImageField(upload_to='')),
            ],
        ),
    ]
