# Generated by Django 2.2.1 on 2019-06-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_delete_doginput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='dog_picture_represented',
        ),
    ]
