# Generated by Django 2.2.1 on 2019-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('user_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
