# Generated by Django 2.2.1 on 2019-05-31 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_apply_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 8, 36, 20, 57884, tzinfo=utc)),
        ),
    ]
