# Generated by Django 2.2.1 on 2019-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepOne', models.CharField(max_length=10)),
                ('stepTwo', models.CharField(max_length=10)),
            ],
        ),
    ]
