# Generated by Django 2.2.1 on 2019-05-31 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_trade_apply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_apply_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
