# Generated by Django 2.2.1 on 2019-06-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190531_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='trade_apply_time',
            new_name='trade_offered_time',
        ),
    ]
